apiVersion: v1
kind: Service
metadata:
  name: nginx-service-np
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 328080
  type: NodePort
