---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: ec2_key          
    region: ap-southeast-1   
    image: ami-0497a974f8d5dcef8
    id: "k3s cluster"
    instance_type: t2.large 
    vpc_id: subnet-0f1685858a5fc2303
    sec_group: "k3s-security-group"
    ec2_access_key: YOUR_ACCESS_KEY
    ec2_secret_key: YOUR_SECRET_KEY

  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        description: "Sec group for app"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}" 
        rules:                               
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ssh port

    - name: Create Key Pair   
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"  
        aws_secret_key: "{{ ec2_secret_key }}" 
        key_material: "{{ lookup('file', '~/.ssh/aws_ec2_key.pub') }}"

    - name: Start server instance
      amazon.aws.ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ vpc_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        network:
          assign_public_ip: true
        image: "{{ image }}"
        instance_tags:
          Name: "server-instance"
      register: server_instance

    - name: Start agent instances
      amazon.aws.ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ vpc_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        network:
          assign_public_ip: true
        image: "{{ image }}"
        count: 2
        instance_tags:
          Name: "agent-instance"
      register: agent_instances

    - name: Get instance facts
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
      register: result

    - name: Display Server Instance ID
      debug:
        msg: "Server Instance ID: {{ server_instance.instances[0].id }}"

    - name: Display Agent Instance IDs
      debug:
        msg: "Agent Instance ID: {{ item.id }}"
      loop: "{{ agent_instances.instances }}"
      tags: always