name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd api
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd api 
        pytest

  build_and_push:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd api
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-api:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.BASTION_HOST }}" >> ~/.ssh/known_hosts

    - name: Test SSH connection to bastion host
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_HOST }} "echo 'SSH connection successful'"
        
    - name: Create SSH tunnel to k3s master
      run: |
        ssh -i ~/.ssh/id_rsa -f -N -L 6443:${{ secrets.K3S_MASTER_IP }}:6443 ubuntu@${{ secrets.BASTION_HOST }}

    # - name: Set up kubeconfig
    #   run: |
    #     echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Deploy to k3s
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
